#애플리케이션 포트설정
server:
  port: 8080

#MySql 연결 설정
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC
    username: juhong
    password: wnghd001!
  devtools:
    livereload:
      enabled: true
  #실행되는 쿼리 콘솔에 출력
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB

#쿼리에 물음표로 출력되는 바인드 파라미터 출력
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace



itemImgLocation: C:/my-workspace/shop/item
uploadPath: file:///C:/my-workspace/shop/